"""Central, environment-driven Apex configuration."""

import os

APP_NAME = "TradeOracle Apex"
VERSION = "2.2.0"

PREDICTION_HORIZON_MINUTES = int(
    os.getenv("APEX_HORIZON_MINUTES", "60")
)

# Live Angel One is the default. Set APEX_DATA_MODE=demo only for offline
# development; no synthetic market prices are generated by the gateway.
DATA_MODE = os.getenv("APEX_DATA_MODE", "live").strip().lower()

DATA_PROVIDER = os.getenv("APEX_DATA_PROVIDER", "").strip()

LIVE_DATA_MAX_AGE_SECONDS = int(
    os.getenv("APEX_LIVE_DATA_MAX_AGE_SECONDS", "120")
)

ANGELONE_EXCHANGE = os.getenv("ANGELONE_EXCHANGE", "NSE").strip().upper()
ANGELONE_SYMBOL = os.getenv("ANGELONE_SYMBOL", "NIFTY").strip()
ANGELONE_SYMBOL_TOKEN = os.getenv("ANGELONE_SYMBOL_TOKEN", "").strip()
ANGELONE_INTERVAL = os.getenv("ANGELONE_INTERVAL", "ONE_MINUTE").strip().upper()
ANGELONE_HISTORY_BARS = int(os.getenv("ANGELONE_HISTORY_BARS", "120"))
ANGELONE_LOOKBACK_MINUTES = int(os.getenv("ANGELONE_LOOKBACK_MINUTES", "240"))

INCOMING_DIR = os.getenv("APEX_INCOMING_DIR", "incoming")

UP_THRESHOLD = float(os.getenv("APEX_UP_THRESHOLD", "0.15"))
DOWN_THRESHOLD = float(os.getenv("APEX_DOWN_THRESHOLD", "-0.15"))

MIN_CONFIDENCE_FOR_SIGNAL = float(
    os.getenv("APEX_MIN_CONFIDENCE", "0.60")
)
