"""Central, environment-driven Apex configuration."""

import os


APP_NAME = "TradeOracle Apex"
VERSION = "2.2.0"


# ---------------------------------------------------------------------------
# PREDICTION HORIZONS
# ---------------------------------------------------------------------------
# The Apex system evaluates multiple forward horizons from the same
# live market context.
#
# 5, 15, 30 and 60 minutes are the supported horizons.
# The primary/default horizon remains 60 minutes for backward compatibility.

PREDICTION_HORIZONS_MINUTES = tuple(
    sorted(
        {
            int(value.strip())
            for value in os.getenv(
                "APEX_HORIZONS_MINUTES",
                "5,15,30,60",
            ).split(",")
            if value.strip()
        }
    )
)

if not PREDICTION_HORIZONS_MINUTES:
    raise ValueError(
        "APEX_HORIZONS_MINUTES must contain at least one valid horizon."
    )

if any(value <= 0 for value in PREDICTION_HORIZONS_MINUTES):
    raise ValueError(
        "APEX_HORIZONS_MINUTES must contain only positive integers."
    )

PREDICTION_HORIZON_MINUTES = int(
    os.getenv(
        "APEX_HORIZON_MINUTES",
        str(max(PREDICTION_HORIZONS_MINUTES)),
    )
)

if PREDICTION_HORIZON_MINUTES not in PREDICTION_HORIZONS_MINUTES:
    raise ValueError(
        "APEX_HORIZON_MINUTES must be one of "
        f"{PREDICTION_HORIZONS_MINUTES}."
    )


# ---------------------------------------------------------------------------
# DATA MODE
# ---------------------------------------------------------------------------

# Live Angel One is the default.
# Demo mode is intended only for offline development.
# No synthetic market prices are generated by the gateway.

DATA_MODE = os.getenv(
    "APEX_DATA_MODE",
    "live",
).strip().lower()

DATA_PROVIDER = os.getenv(
    "APEX_DATA_PROVIDER",
    "",
).strip()


# ---------------------------------------------------------------------------
# LIVE DATA
# ---------------------------------------------------------------------------

LIVE_DATA_MAX_AGE_SECONDS = int(
    os.getenv(
        "APEX_LIVE_DATA_MAX_AGE_SECONDS",
        "120",
    )
)


# ---------------------------------------------------------------------------
# ANGEL ONE
# ---------------------------------------------------------------------------

ANGELONE_EXCHANGE = os.getenv(
    "ANGELONE_EXCHANGE",
    "NSE",
).strip().upper()

ANGELONE_SYMBOL = os.getenv(
    "ANGELONE_SYMBOL",
    "NIFTY",
).strip()

ANGELONE_SYMBOL_TOKEN = os.getenv(
    "ANGELONE_SYMBOL_TOKEN",
    "",
).strip()

ANGELONE_INTERVAL = os.getenv(
    "ANGELONE_INTERVAL",
    "ONE_MINUTE",
).strip().upper()

ANGELONE_HISTORY_BARS = int(
    os.getenv(
        "ANGELONE_HISTORY_BARS",
        "120",
    )
)

ANGELONE_LOOKBACK_MINUTES = int(
    os.getenv(
        "ANGELONE_LOOKBACK_MINUTES",
        "240",
    )
)


# ---------------------------------------------------------------------------
# RUNTIME
# ---------------------------------------------------------------------------

INCOMING_DIR = os.getenv(
    "APEX_INCOMING_DIR",
    "incoming",
)


# ---------------------------------------------------------------------------
# DECISION THRESHOLDS
# ---------------------------------------------------------------------------

UP_THRESHOLD = float(
    os.getenv(
        "APEX_UP_THRESHOLD",
        "0.15",
    )
)

DOWN_THRESHOLD = float(
    os.getenv(
        "APEX_DOWN_THRESHOLD",
        "-0.15",
    )
)

MIN_CONFIDENCE_FOR_SIGNAL = float(
    os.getenv(
        "APEX_MIN_CONFIDENCE",
        "0.60",
    )
)

MIN_HISTORY_BARS = int(
    os.getenv(
        "APEX_MIN_HISTORY_BARS",
        "30",
    )
)


# ---------------------------------------------------------------------------
# DATA SAFETY
# ---------------------------------------------------------------------------

REQUIRE_FRESH_DATA_FOR_SIGNAL = os.getenv(
    "APEX_REQUIRE_FRESH_DATA_FOR_SIGNAL",
    "true",
).strip().lower() not in {
    "0",
    "false",
    "no",
    "off",
}


# ---------------------------------------------------------------------------
# NEWS
# ---------------------------------------------------------------------------

NEWS_LOOKBACK_HOURS = int(
    os.getenv(
        "APEX_NEWS_LOOKBACK_HOURS",
        "24",
    )
)
